# frozen_string_literal: true

require 'fileutils'
require 'json'
require 'asciidoctor'
require 'yaml'
require 'date'

# Load DocOps Lab development tooling
require 'docopslab/dev'

# Include Git branch utilities
# rubocop:disable Style/MixinUsage
extend DocOpsLab::Dev::GitBranch
# rubocop:enable Style/MixinUsage

# Configuration
JEKYLL_CONFIG = YAML.load_file('_config.yml')
DEPLOY_BRANCH = 'gh-pages'
LIBRARY_BRANCH = 'labdev-library'
BUILD_DIR = JEKYLL_CONFIG['destination'] || '_site'
SLIDES_DIR = 'slides'
PROJECTS_DATA = YAML.safe_load_file('_data/docops-lab-projects.yml', permitted_classes: [Date])

desc 'Extract AsciiDoc attributes for single-sourcing'
task :extract_readme_attrs do
  puts '🔎 Extracting AsciiDoc attributes from README.adoc...'
  attrs = {}
  doc = Asciidoctor.load_file('README.adoc', safe: :safe)
  sensitive_keys = %w[user-home docfile docdir]
  sensitive_keys.each { |key| doc.attributes.delete(key) if doc.attributes.key?(key) }
  doc.attributes.each do |key, value|
    if key.end_with?('-desc') && value && !value.empty?
      attrs[key.sub('-desc', '')] = value
    else
      attrs[key] = value
    end
  end
  FileUtils.mkdir_p('_data/built')
  File.write('_data/built/attrs.yml', attrs.to_yaml)
  puts '✅ Extracted to _data/built/attrs.yml'
end

desc 'Validate projects YAML file'
task :validate_projects do
  require_relative 'scripts/validate-projects-yaml'

  file_path = '_data/docops-lab-projects.yml'
  puts "🔍 Validating #{file_path}..."
  validator = ProjectsYAMLValidator.new(file_path)

  exit 1 unless validator.validate
end

# Utility: Convert arbitrary HTML to Markdown using our ReverseMarkdown extensions
namespace :util do
  desc 'Convert HTML to Markdown (args: source, dest). Uses MarkDownGrade and writes to .agent by default.'
  task :html_to_md, [:source, :dest] do |_, args|
    require 'nokogiri'
    require_relative 'scripts/mark_down_grade'

    MarkDownGrade.bootstrap!

    source = args[:source] || File.join(BUILD_DIR, 'metablog', 'tech-blogging-in-asciidoc', 'index.html')
    dest   = args[:dest]   || File.join('.agent', 'converted', 'metablog-tech-blogging-in-asciidoc.md')

    unless File.exist?(source)
      puts "🔨 Building site to generate #{source}..."
      Rake::Task['build_site'].invoke
    end

    unless File.exist?(source)
      puts "❌ Source HTML not found: #{source}"
      next
    end

    html = File.read(source)
    doc = Nokogiri::HTML(html)

    # Prefer specific content wrappers to avoid bringing site chrome
    container = doc.at_css('div.document-body') ||
                doc.at_css('div.post-content.metablog') ||
                doc.at_css('div.post-content') ||
                doc.at_css('article.blog-post .post-content') ||
                doc.at_css('article.blog-post') ||
                doc.at_css('article') ||
                doc.at_css('main') ||
                doc.at_css('body')

    if container.nil?
      puts "❌ Could not find content container in #{source}"
      next
    end

    # Remove non-content bits inside the container
    container.css(
      'script,
       style,
       nav,
       .post-navigation,
       .back-to-metablog,
       .back-to-blog,
       .metablog-banner,
       footer').remove

    markdown = MarkDownGrade.convert(container.inner_html, github_flavored: true)

    FileUtils.mkdir_p(File.dirname(dest))
    File.write(dest, markdown)
    puts "✅ Wrote #{dest}"
  end
end

desc 'Generate project pages from project data (AsciiDoc)'
task :generate_project_pages do
  puts '📄 Generating project pages (.adoc)...'

  # Create _projects directory if it doesn't exist
  FileUtils.mkdir_p('_projects')

  # Load project data
  projects_data = PROJECTS_DATA
  projects = projects_data['projects']
  # select only projects with page or star (not nil)
  paged_projects = projects.select { |p| p['page'] || p['star'] }

  # Clear existing project pages
  Dir.glob('_projects/*.adoc').each { |f| File.delete(f) }

  paged_projects.each do |project|
    slug = project['slug'] || project['name']&.downcase&.gsub(/[^a-z0-9\-_]/, '-')
    next unless slug

    filename = "_projects/#{slug}.adoc"

    # Generate frontmatter
    project_name = project['name'] || slug.split('-').map(&:capitalize).join(' ')
    frontmatter = {
      'layout' => 'projects',
      'title' => project_name,
      'slug' => slug,
      'type' => 'profile',
      'generated' => true,
      'generation_date' => Time.now.strftime('%Y-%m-%d %H:%M:%S'),
      'liquid' => true
    }

    # Add optional fields if present
    frontmatter['category'] = project['type'] if project['type']
    frontmatter['status'] = project['done'] ? 'live' : 'development' if project.key?('live')
    frontmatter['tags'] = project['tags'] if project['tags']

    # Create the file content
    content = "#{frontmatter.to_yaml}---\n\n"
    content += "// This page is auto-generated by rake generate_project_pages\n"
    content += "// Source data: _data/docops-lab-projects.yml\n\n"
    content += "++++\n"
    content += "{% include project-page.html slug=page.slug %}\n"
    content += "++++\n"

    # Write the file
    File.write(filename, content)
    puts "  ✓ Generated #{filename}"
  end

  puts "✅ Generated #{paged_projects.count} project pages (.adoc)"
end

desc 'Generate metadata master files for projects'
task :generate_metadata do
  puts '📊 Generating project metadata...'

  # Load project data
  projects_data = PROJECTS_DATA
  projects = projects_data['projects']

  # Collect unique tags and tech and make a types dictionary
  tags = projects.flat_map { |p| p['tags'] || [] }.uniq.sort
  tech = projects.flat_map { |p| p['tech'] || [] }.uniq.sort
  # generate type parameters from $meta['types'] based on text: defaulting to head:
  # should yield like:
  # types:
  #   content: Content Repos
  #   rest-api: REST API
  types = projects_data['$meta']['types'].each_with_object({}) do |type_info, hash|
    slug = type_info['slug']
    display_text = type_info['text'] || type_info['slug']
    hash[slug] = display_text
  end
  # Write to metadata file
  metadata = {
    'tags' => tags,
    'tech' => tech,
    'types' => types
  }

  File.write('_data/built/projects_metadata.yml', metadata.to_yaml)

  puts '✅ Project metadata generated at _data/built/projects_metadata.yml'
end

desc 'Copy the Jekyll-AsciiDoc UI config definition file'
task :copy_jekyll_ui_config do
  pwd = Dir.pwd
  source = '../jekyll-asciidoc-ui/specs/data/config-def.yml'
  if pwd == '/workspace'
    puts "⚠️  Warning: Containerized environment cannot see #{source}; skipping copy."
    next
  end
  dest_dir = '_data/'
  dest = File.join(dest_dir, 'jekyll-asciidoc-ui-config-def.yml')

  unless File.exist?(source)
    puts "⚠️  Source file #{source} does not exist. Skipping jekyll-asciidoc-ui config copy (CI/standalone mode)."
    next
  end

  FileUtils.mkdir_p(dest_dir)
  FileUtils.cp(source, dest)
  puts "✅ Copied Jekyll-AsciiDoc UI config definition to #{dest}"
end

desc 'Write RuboCop styles configuration file'
task :write_rubocop_styles do
  FileUtils.mkdir_p('_docs/partials/built')
  build_cmd = 'bundle exec ruby scripts/rubocop_styles_adoc.rb ' \
              'gems/docopslab-dev/assets/config-packs/rubocop/base.yml > ' \
              '_docs/partials/built/_rubocop-styles.adoc'
  system(build_cmd) or raise 'Failed to generate RuboCop styles'
  puts '✅ RuboCop styles written to _docs/partials/built/_rubocop-styles.adoc'
end

desc 'Render an AsciiDoc file of universal attributes'
# use _data/docops-lab-projects.yml data and the Liquid template at _includes/docopslab-universal-attributes.asciidoc to produce a file at _docs/partials/built/_docopslab-universal-attributes.adoc
task :generate_universal_attributes do
  puts '📄 Generating universal attributes AsciiDoc file...'

  # Load project data
  projects_data = PROJECTS_DATA

  # Prepare Liquid template
  template_path = '_includes/docopslab-universal-attributes.asciidoc'
  unless File.exist?(template_path)
    puts "❌ Template file not found: #{template_path}"
    exit 1
  end
  template_content = File.read(template_path)

  # Render Liquid template with project data
  require 'liquid'
  liquid_template = Liquid::Template.parse(template_content)
  rendered_content = liquid_template.render('site' => { 'data' => { 'docops-lab-projects' => projects_data } })

  # Write to destination file
  dest_path = '_docs/partials/built/_docopslab-universal-attributes.adoc'
  FileUtils.mkdir_p(File.dirname(dest_path))
  File.write(dest_path, rendered_content)

  puts "✅ Generated universal attributes at #{dest_path}"
end

desc 'Build DocOpsLab Vale package for distribution'
task :build_vale_package do
  system('bundle exec ruby scripts/build_vale_package.rb') or raise 'Failed to build Vale package'
end

desc 'Build the Jekyll site (with single-sourced cards and project pages)'
task build_site: %i[extract_readme_attrs generate_project_pages generate_metadata copy_jekyll_ui_config
                    write_rubocop_styles generate_universal_attributes gemdo:gen_agent_docs] do
  puts '🔨 Building Jekyll site...'
  system('bundle exec jekyll build') or raise 'Jekyll build failed'
  puts '✅ Build complete'
end

desc 'Serve the site locally for development (with single-sourced cards and project pages)'
task serve: [:build_site] do
  port = ENV['PORT'] || '4000'
  puts "🚀 Starting Jekyll development server on port #{port}..."
  serve_cmd = "bundle exec jekyll serve --watch --livereload --port #{port} --skip-initial-build"
  system(serve_cmd) or raise 'Jekyll serve failed'
end

namespace :review do
  desc 'Fetch and serve a PR review build from GitHub Actions artifact'
  task :serve do
    require 'fileutils'
    require 'tmpdir'
    require 'json'

    sha = ENV['SHA'] || abort('❌ SHA environment variable required (e.g., SHA=abc123 rake review:serve)')
    port = ENV['PORT'] || '4001'
    repo = 'DocOps/lab'

    puts "🔍 Fetching artifact for commit #{sha[0..7]}..."

    # Check if gh CLI is available
    unless system('which gh > /dev/null 2>&1')
      abort('❌ GitHub CLI (gh) not found. Install using your system\'s package manager (or see https://cli.github.com/)')
    end

    # Create temp directory for review
    review_dir = File.join(Dir.tmpdir, 'docops-lab-review', sha)
    FileUtils.mkdir_p review_dir

    # Find workflow run for this SHA
    puts '🔎 Finding workflow run...'
    run_json = `gh run list --repo #{repo} --json databaseId,status,conclusion,name,headSha --limit 20`
    runs = JSON.parse(run_json)

    # Filter for runs matching this SHA and the main workflow
    matching_runs = runs.select { |r| r['headSha'].start_with?(sha) && r['name'] == 'Main CI/CD Pipeline' }

    abort("❌ No workflow runs found for commit #{sha[0..7]}") if matching_runs.empty?

    run = matching_runs.find { |r| r['status'] == 'completed' && r['conclusion'] == 'success' }

    if run.nil?
      in_progress = matching_runs.find { |r| r['status'] == 'in_progress' }
      if in_progress
        abort('⏳ Workflow is still running for this commit. Wait for it to complete.')
      else
        abort("❌ No successful workflow run found for commit #{sha[0..7]}")
      end
    end

    run_id = run['databaseId']
    puts "✓ Found workflow run ##{run_id}"

    # Get artifacts for this run to find the actual site artifact name
    puts '🔎 Finding site artifact...'
    artifacts_json = `gh api repos/#{repo}/actions/runs/#{run_id}/artifacts`
    artifacts = JSON.parse(artifacts_json)['artifacts']
    site_artifact = artifacts.find { |a| a['name'].start_with?('site-') }

    abort('❌ No site artifact found for this run') unless site_artifact
    artifact_name = site_artifact['name']

    # Check if site is already cached
    if File.exist?(File.join(review_dir, 'index.html'))
      puts "✓ Using cached site from #{review_dir}"
    else
      puts "📦 Downloading #{artifact_name}..."
      Dir.chdir(review_dir) do
        result = system("gh run download #{run_id} --repo #{repo} --name #{artifact_name}")
        abort('❌ Failed to download artifact') unless result
      end
    end

    puts "✅ Review site ready at #{review_dir}"
    puts "🚀 Starting server on http://localhost:#{port}..."
    puts '   (Press Ctrl+C to stop)'
    puts ''

    # Serve with Jekyll, specifying the source directory
    serve_cmd = "bundle exec jekyll serve --watch --port #{port} --skip-initial-build --source #{review_dir}"
    system(serve_cmd) or abort('❌ Server failed')
  end
end

desc 'Show drafts stored in standby-content branch'
# Displays any .adoc or .md files in the standby-content branch that are not in the current branch, for easy review of in-progress content without switching branches.
task :show_drafts do
  current_branch = git_current_branch
  standby_branch = 'standby-content'

  puts "🔍 Comparing #{current_branch} with #{standby_branch} for draft content...\n\n"

  # Get list of .adoc and .md files in both branches
  standby_files = `git ls-tree -r --name-only #{standby_branch}`.split("\n").select { |f| f.end_with?('.adoc', '.md') }
  current_files = `git ls-tree -r --name-only #{current_branch}`.split("\n").select { |f| f.end_with?('.adoc', '.md') }

  # Files in standby but not in current
  draft_files = standby_files - current_files

  if draft_files.empty?
    puts "✅ No draft files found in #{standby_branch}"
    next
  end

  puts "📄 Draft files in #{standby_branch} not in #{current_branch}:"
  puts '━' * 80

  draft_files.each do |file|
    # Get file content from standby branch
    file_content = `git show #{standby_branch}:#{file} 2>/dev/null`

    # Get last commit date for the file
    last_commit = `git log -1 --format=%ai #{standby_branch} -- #{file} 2>/dev/null`.strip

    # Extract metadata
    metadata = extract_draft_metadata(file, file_content)

    # Display file info
    puts "\n📝 #{file}"
    puts "   Last update: #{last_commit}" if last_commit.length.positive?

    # Display metadata if found
    puts "   Title: #{metadata[:title]}" if metadata[:title]
    puts "   Description: #{metadata[:description]}" if metadata[:description]
    puts "   Date: #{metadata[:date]}" if metadata[:date]
    puts "   Tags: #{metadata[:tags]}" if metadata[:tags]
    puts "   Excerpt: #{metadata[:excerpt]}" if metadata[:excerpt]
  end

  puts "\n#{'━' * 80}"
  puts "✅ Found #{draft_files.size} draft file(s) in #{standby_branch}"
end

# Helper method to extract metadata from .adoc or .md files
def extract_draft_metadata filename, content
  metadata = {}

  # Extract frontmatter YAML from both .adoc and .md files
  metadata.merge!(parse_frontmatter_yaml(content))

  # For .adoc files, also extract AsciiDoc document attributes
  return metadata unless filename.end_with?('.adoc')

  # Suppress Asciidoctor warnings for this parsing
  original_stderr = $stderr
  $stderr = File.open(File::NULL, 'w')
  begin
    doc = Asciidoctor.load(content, safe: :safe)

    # Extract title from document or frontmatter
    metadata[:title] ||= doc.doctitle if doc.doctitle

    # Extract page- attributes
    %w[date tags excerpt description].each do |attr|
      doc_key = "page-#{attr}"
      metadata[attr.to_sym] = doc.attributes[doc_key] if doc.attributes[doc_key]
    end
  rescue StandardError
    # Skip files that fail to parse
  ensure
    $stderr = original_stderr
  end

  metadata
end

# Helper to extract and parse YAML frontmatter
def parse_frontmatter_yaml content
  return {} unless content.start_with?('---')

  fm_end = content.index(/^---/, 3)
  return {} unless fm_end

  fm_content = content[3...fm_end].strip
  begin
    parsed_fm = YAML.safe_load(fm_content) || {}
    parsed_fm.transform_keys { |k| k.to_s.downcase.to_sym }
  rescue Psych::SyntaxError
    # Silently skip malformed frontmatter
    {}
  end
end

desc 'Clean build artifacts'
task :clean do
  puts '🧹 Cleaning build artifacts...'
  FileUtils.rm_rf(BUILD_DIR)
  FileUtils.rm_rf('.jekyll-cache')
  puts '✅ Clean complete'
end

desc 'Update slides from docs-as-code-school repo'
task :update_slides do
  puts '📊 Updating slides from docs-as-code-school...'
  system('./scripts/copy-slides.sh') or raise 'Slides update failed'
  puts '✅ Slides updated'
end

desc 'Switch to gh-pages branch (for manual inspection)'
task :switch_to_deploy do
  current_branch = git_current_branch
  git_ensure_clean_switch!(DEPLOY_BRANCH)

  puts "📦 Switching to #{DEPLOY_BRANCH} branch..."

  system("git checkout #{DEPLOY_BRANCH}") or raise "Failed to checkout #{DEPLOY_BRANCH}"
  puts "✅ Now on #{DEPLOY_BRANCH} branch. Use 'git checkout #{current_branch}' to return."
end

desc 'Prepare deployment files (SAFE - does not commit or push)'
task prepare_deploy: %i[clean build_site] do
  puts '🚀 Preparing deployment files...'

  # Save current branch and ensure clean state
  current_branch = git_current_branch
  git_ensure_clean_switch!(DEPLOY_BRANCH)

  # Store the current commit hash
  `git rev-parse HEAD`.strip

  begin
    # Switch to deploy branch
    puts "📦 Switching to #{DEPLOY_BRANCH} branch..."
    system("git checkout #{DEPLOY_BRANCH}") or raise "Failed to checkout #{DEPLOY_BRANCH}"

    # Clear everything except .git and slides/
    puts '🧹 Clearing deploy branch (preserving slides/)...'
    Dir.glob('*', File::FNM_DOTMATCH).each do |item|
      next if ['.', '..', '.git', SLIDES_DIR].include?(item)

      FileUtils.rm_rf(item)
    end

    # Copy built site contents to root
    puts '📋 Copying built site to deploy branch...'
    Dir.glob("#{BUILD_DIR}/*", File::FNM_DOTMATCH).each do |item|
      next if ['.', '..'].include?(File.basename(item))

      dest = File.basename(item)
      # Don't overwrite slides/ if it exists in the build
      if dest == SLIDES_DIR && File.exist?(SLIDES_DIR)
        puts "⚠️  Preserving existing #{SLIDES_DIR}/ directory"
        next
      end
      FileUtils.cp_r(item, dest)
    end

    # Create a minimal .gitignore for gh-pages branch
    File.write('.gitignore', <<~GITIGNORE)
      # Only ignore truly temporary files in the deploy branch
      .DS_Store
      *.tmp
      *.log
    GITIGNORE

    puts '✅ Deployment files prepared!'
    puts "📝 You are now on the #{DEPLOY_BRANCH} branch."
    puts '🔍 Review the changes with: git status'
    puts '📦 Commit when ready with: rake commit_deploy'
    puts "🔄 Return to main branch with: git checkout #{current_branch}"
  rescue StandardError => e
    puts "❌ Preparation failed: #{e.message}"
    # Always return to original branch on error
    puts "🔄 Returning to #{current_branch} branch..."
    system("git checkout #{current_branch}")
    exit 1
  end
end

desc 'Commit deployment (run this after prepare_deploy and review)'
task :commit_deploy do
  current_branch = git_current_branch

  unless current_branch == DEPLOY_BRANCH
    puts "❌ You must be on the #{DEPLOY_BRANCH} branch to commit deployment."
    puts "� Run 'rake prepare_deploy' first."
    exit 1
  end

  # Get the main branch commit hash for reference
  main_commit = `git rev-parse main`.strip

  puts '�💾 Committing deployment...'
  system('git add -A')
  commit_message = "Deploy from main branch (#{main_commit[0..7]})"

  if system("git commit -m '#{commit_message}'")
    puts '✅ Deployment committed!'
    puts '🌐 Push to origin with: rake push_deploy'
    puts '🔄 Return to main branch with: git checkout main'
  else
    puts '⚠️  No changes to commit or commit failed'
  end
end

desc 'Push deployment to origin (DANGER: this updates the live site!)'
task :push_deploy do
  current_branch = git_current_branch

  unless current_branch == DEPLOY_BRANCH
    puts "❌ You must be on the #{DEPLOY_BRANCH} branch to push deployment."
    puts "💡 Run 'rake prepare_deploy' and 'rake commit_deploy' first."
    exit 1
  end

  puts '⚠️  WARNING: This will update the live site at https://docopslab.org'
  puts '🤔 Are you sure you want to continue? (yes/no)'

  response = $stdin.gets.chomp.downcase
  unless %w[yes y].include?(response)
    puts '❌ Push cancelled.'
    exit 0
  end

  puts '🌐 Pushing to origin...'
  if system("git push origin #{DEPLOY_BRANCH}")
    puts '✅ Deployment pushed to origin!'
    puts '🌐 Site updated at: https://docopslab.org'
  else
    puts '❌ Push failed!'
    exit 1
  end
end

desc 'Full deployment (prepare + commit + push)'
task deploy: %i[prepare_deploy commit_deploy push_deploy]

desc 'Safe deployment workflow (prepare only - no commit/push)'
task deploy_safe: [:prepare_deploy]

desc 'Deploy with slides update (full workflow)'
task deploy_with_slides: %i[update_slides deploy]

desc 'Safe deploy with slides update (prepare only)'
task deploy_with_slides_safe: %i[update_slides deploy_safe]

desc 'Return to main branch from gh-pages'
task :return_to_main do
  current_branch = git_current_branch
  if current_branch == DEPLOY_BRANCH
    puts '🔄 Returning to main branch...'
    system('git checkout main')
    puts '✅ Back on main branch'
  else
    puts "ℹ️  Already on #{current_branch} branch"
  end
end

# namespace 'gemdo' for docopslab-dev gem/project related tasks
namespace :gemdo do
  desc 'Build the DocOps Lab Dev Docker image'
  task :build_docker do
    Rake::Task['build_site'].invoke

    # get the image version
    version = DocOpsLab::Dev::VERSION
    puts "🐳 Building DocOps Lab Dev Docker image version #{version}..."
    build_cmd = "VERSION=#{version} ./gems/docopslab-dev/build-docker.sh"
    system(build_cmd) or raise 'Failed to build DocOps Lab Dev Docker image'
    puts '✅ Docker image built successfully'
  end

  desc 'Build docopslab-dev gem package to gems/docopslab-dev/pkg/'
  task :build_gem do
    Rake::Task['gemdo:gen_agent_docs'].invoke
    puts '💎 Building docopslab-dev gem package...'
    Dir.chdir('gems/docopslab-dev') do
      system('gem build docopslab-dev.gemspec') or raise 'Failed to build docopslab-dev gem'
      FileUtils.mkdir_p('pkg')
      built_gem = Dir.glob('docopslab-dev-*.gem').max_by { |f| File.mtime(f) }
      FileUtils.mv(built_gem, 'pkg/')
      puts "✅ docopslab-dev gem built at gems/docopslab-dev/pkg/#{File.basename(built_gem)}"
    end
  end

  desc 'Generate agent documentation for docopslab-dev gem'
  task :gen_agent_docs do
    require_relative 'scripts/gen_agent_docs'

    # Build Jekyll site if not already built (for agent docs HTML)
    unless Dir.exist?(BUILD_DIR) && !Dir.empty?(BUILD_DIR)
      puts '📄 Building Jekyll site for agent docs HTML...'
      system('bundle exec jekyll build') or raise 'Jekyll build failed'
    end

    # Run the generation script
    GenAgentDocs.run(BUILD_DIR)
  end

  desc 'Test all labdev rake tasks using definitions from tasks-def.yml'
  task :test_tasks, [:filter1, :filter2, :filter3] do |_t, args|
    puts '🧪 Running labdev tasks test suite...'

    # Build command with optional filters
    cmd = 'ruby scripts/test_labdev_tasks.rb'

    # Collect all non-nil filter arguments
    filters = [args[:filter1], args[:filter2], args[:filter3]].compact

    cmd += " #{filters.join(' ')}" if filters.any?

    system(cmd) or raise 'Task tests failed'
  end

  # Staging and publishing the remote library to the labdev-library branch.
  # .library/ is the untracked local staging dir (rebuilt on demand).
  # LibraryManager reads gems/docopslab-dev/specs/data/library-index.yml.
  namespace :push do
    require_relative 'scripts/library_manager'

    namespace :library do
      desc 'Run all library prebuild steps declared in library-index.yml'
      task :prebuild do
        LibraryManager.prebuild_tasks.each do |task_name|
          puts "🔧 Library prebuild: #{task_name}"
          Rake::Task[task_name].invoke
        end
        puts '✅ Library prebuild complete'
      end

      desc "Stage library assets into #{LibraryManager::STAGE_DIR}/ using library-index.yml"
      task stage: %w[gemdo:push:library:prebuild] do
        LibraryManager.stage!
      end

      desc "Generate #{LibraryManager::STAGE_DIR}/#{LibraryManager::CATALOG_FILE} with SHA256 checksums"
      task :generate_catalog do
        LibraryManager.generate_catalog!(DocOpsLab::Dev::VERSION)
      end

      desc "Load #{LibraryManager::STAGE_DIR}/ into the host XDG cache for local testing (no GitHub push)"
      task local: %w[gemdo:push:library:stage gemdo:push:library:generate_catalog] do
        raise 'Catalog not found; run gemdo:push:library:generate_catalog first' unless LibraryManager.staged?

        puts "📥 Installing #{LibraryManager::STAGE_DIR}/ into host cache..."
        DocOpsLab::Dev::Library::Cache.write!(LibraryManager::STAGE_DIR)
        puts "✅ Library installed to #{DocOpsLab::Dev::Library::Cache.current_path}"
        puts '   Run `bundle exec rake labdev:show:library` in any downstream project to verify.'
      end

      desc "Force-push #{LibraryManager::STAGE_DIR}/ to the #{LIBRARY_BRANCH} branch on GitHub"
      task :remote do
        require 'tmpdir'

        raise "#{LibraryManager::STAGE_DIR}/ not found; run gemdo:push:library:stage first" \
          unless Dir.exist?(LibraryManager::STAGE_DIR)
        raise "#{LibraryManager.catalog_path} not found; run gemdo:push:library:generate_catalog first" \
          unless File.exist?(LibraryManager.catalog_path)

        remote_url = `git remote get-url origin 2>/dev/null`.strip
        raise 'Could not determine remote origin URL' if remote_url.empty?

        stage = LibraryManager::STAGE_DIR
        puts "🚀 Pushing #{stage}/ to branch #{LIBRARY_BRANCH} on #{remote_url}..."

        Dir.mktmpdir('labdev-push-') do |tmpdir|
          system('git', 'init', tmpdir) or raise 'git init failed'
          system('git', '-C', tmpdir, 'checkout', '-b', LIBRARY_BRANCH) or raise 'git checkout failed'

          Dir.glob("#{stage}/**/*", File::FNM_DOTMATCH).each do |src|
            next if File.directory?(src)
            next if File.basename(src).start_with?('.')

            rel  = Pathname.new(src).relative_path_from(Pathname.new(stage)).to_s
            dest = File.join(tmpdir, rel)
            FileUtils.mkdir_p(File.dirname(dest))
            FileUtils.cp(src, dest)
          end

          ts = begin
            JSON.parse(File.read(LibraryManager.catalog_path))['generated_at']
          rescue StandardError
            'unknown'
          end
          system('git', '-C', tmpdir, 'add', '.') or raise 'git add failed'
          system(
            'git', '-C', tmpdir, 'commit', '--allow-empty', '-m',
            "auto: update library (#{ts})") or raise 'git commit failed'
          system('git', '-C', tmpdir, 'remote', 'add', 'origin', remote_url) or raise 'git remote add failed'
          push_env = { 'GIT_SSH_COMMAND' => 'ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new' }
          puts "  → pushing to #{remote_url}..."
          system(
            push_env, 'git', '-C', tmpdir, 'push', '--force', 'origin',
            LIBRARY_BRANCH) or raise "git push to #{LIBRARY_BRANCH} failed"
        end

        puts "✅ Library pushed to #{LIBRARY_BRANCH}"
      end
    end

    desc 'Prebuild, stage, & generate catalog only; no GH push'
    task dry: %w[gemdo:push:library:stage gemdo:push:library:generate_catalog]

    desc 'Prebuild, stage, generate catalog, and push library to labdev-library on GitHub'
    task library: %w[gemdo:push:library:stage gemdo:push:library:generate_catalog gemdo:push:library:remote]
  end
end
